### PR TITLE
Lamdera support

### PR DESCRIPTION
**Pull request by MartinSStewart**
Lamdera packages aren't available from the Elm package ecosystem which is a problem whenever I want to use this tool with a Lamdera app's elm.json. To solve this, I've hard coded in the Lamdera packages

### CODE REVIEW

**Comment by supermario** [comment]
FYI the way that Lamdera loads `lamdera/*` packages is via the pattern:

```
https://static.lamdera.com/r/author/package/version/filename
```

i.e.

```
https://static.lamdera.com/r/lamdera/core/1.0.0/elm.json
```

So that could be another hardcoding alternative to hardcoding the json contents.

**Comment by MartinSStewart** [comment]
Ah okay, maybe it's better to use that then. Is there an endpoint for getting all versions of a specific lamdera package as well?

**Comment by MartinSStewart** [comment]
@supermario I tried using `https://static.lamdera.com/r/lamdera/core/1.0.0/elm.json` but it turns out that it gets blocked by CORS. I think it's best to just go with hard coding everything for now.

**Comment by MartinSStewart** [comment]
@synalysis I can't make an issue for this repo so I'll just write it here that the description for this repo points towards the old dependency analyzer url instead of the new one. 
image

**Review by synalysis — APPROVED** [review]

**Comment by synalysis** [comment]
Thank you, Martin! Just updated on the server.

**Pull request merged**
